export const LOCATIONS = new Map([
  ["apac", "APAC"],
  ["emea", "EMEA"],
  ["latam", "LATAM"],
  ["argentina", "Argentina"],
  ["australia", "Australia"],
  ["austria", "Austria"],
  ["belgium", "Belgium"],
  ["brazil", "Brazil"],
  ["bulgaria", "Bulgaria"],
  ["canada", "Canada"],
  ["china", "China"],
  ["hong-kong", "Hong Kong"],
  ["costa-rica", "Costa Rica"],
  ["croatia", "Croatia"],
  ["cyprus", "Cyprus"],
  ["czechia", "Czechia"],
  ["denmark", "Denmark"],
  ["estonia", "Estonia"],
  ["europe", "Europe"],
  ["finland", "Finland"],
  ["france", "France"],
  ["germany", "Germany"],
  ["greece", "Greece"],
  ["hungary", "Hungary"],
  ["ireland", "Ireland"],
  ["israel", "Israel"],
  ["italy", "Italy"],
  ["japan", "Japan"],
  ["latvia", "Latvia"],
  ["lithuania", "Lithuania"],
  ["mexico", "Mexico"],
  ["netherlands", "Netherlands"],
  ["new-zealand", "New Zealand"],
  ["norway", "Norway"],
  ["philippines", "Philippines"],
  ["poland", "Poland"],
  ["portugal", "Portugal"],
  ["romania", "Romania"],
  ["serbia", "Serbia"],
  ["singapore", "Singapore"],
  ["slovakia", "Slovakia"],
  ["slovenia", "Slovenia"],
  ["south-korea", "South Korea"],
  ["spain", "Spain"],
  ["sweden", "Sweden"],
  ["switzerland", "Switzerland"],
  ["thailand", "Thailand"],
  ["turkiye", "Türkiye"],
  ["united-arab-emirates", "UAE"],
  ["uk", "UK"],
  ["ukraine", "Ukraine"],
  ["usa", "USA"],
  ["vietnam", "Vietnam"],
]);

export const INDUSTRIES = new Map([
  ["admin-support", "Admin & Virtual Assistant"],
  ["business", "Business Development"],
  ["copywriting", "Content & Editorial"],
  ["design-multimedia", "Creative & Design"],
  ["supporting", "Customer Success"],
  ["data-science", "Data Science & Analytics"],
  ["admin", "DevOps & Infrastructure"],
  ["education", "Education & E-learning"],
  ["accounting-finance", "Finance & Accounting"],
  ["healthcare", "Healthcare & Medical"],
  ["hr", "HR & Recruiting"],
  ["marketing", "Marketing & Sales"],
  ["management", "Product & Operations"],
  ["dev", "Programming"],
  ["seller", "Sales"],
  ["seo", "SEO"],
  ["smm", "Social Media Marketing"],
  ["engineering", "Software Engineering"],
  ["technical-suppor", "Technical Support"],
  ["web-app-design", "Web & App Design"],
]);

export const JOBICY_BASE_URL = "https://jobicy.com/api/v2/remote-jobs";

export const BASE_URL = process.env.BASE_URL || 'http://localhost:3000'